EBApi/urls.py
"""Defines URL patterns for EBApi."""

from django.urls import path

from . import views

app_name = 'EBApi'
urlpatterns = [
    # Home page
    path('', views.properties, name='index'),
    # Property List 
    path('properties/<int:page>', views.properties, name="properties"),
    path('properties/', views.properties, name="properties"),
    # Property Detail
    path('property/<str:id>', views.property_detail, name="property"),
    # Contact request form
    path('contact_request/<str:id>', views.contact_request, name="contact_requests"),
]

pruebaEB/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('EBApi.urls')),
]

EBApi/models.py
from django.db import models

# Create your models here.

EBApi/forms.py
from django import forms

class ContactRequestForm(forms.Form):
    """A client's contact request form."""

    name = forms.CharField(max_length=12)
    phone = forms.CharField(max_length=255)
    email = forms.EmailField(max_length=255)
    public_id = forms.CharField(max_length=9, widget=forms.HiddenInput())
    message = forms.CharField(max_length=255)
    

EBApi/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseRedirect

from .forms import ContactRequestForm

import requests

#############
# FUNCTIONS #
#############

def make_request(url):
    """Generates a response."""

    headers = {
        'X-Authorization': 'l7u502p8v46ba3ppgvj5y2aad50lb9'
    }

    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        response = response.json()
        return response

def send_request(data):
    """Sends a contact request."""

    url = "https://api.stagingeb.com/v1/contact_requests"
    payload = {'data': data}
    headers = {
        'X-Authorization': 'l7u502p8v46ba3ppgvj5y2aad50lb9'
    }
    res = requests.post(url, data=payload, headers=headers)


#########
# VIEWS #
#########

def properties(request, page=1):
    """Lists a page of properties."""

    url = f'https://api.stagingeb.com/v1/properties?page={page}&limit=15&search%5Bstatuses%5D%5B%5D=published'

    response = make_request(url)

    # Obtains the number of the following page.
    # Reads the url from the response and splits it to obtain the number of the 
    # page.
    # If there isn't a next page, it returns None.
    next_page = response['pagination']['next_page']
    if next_page:
        next_page = next_page.split('&')
        next_page = next_page[1].split('=')
        next_page = next_page[1]

    # Obtains the previous page number.
    previous_page = page - 1
    if previous_page == 0:
        previous_page = None

    context = {
        'properties': response['content'], 
        'next_page': next_page,
        'previous_page': previous_page,
    }

    return render(request, 'EBApi/properties.html', context)

def property_detail(request, id):
    """Displays a property information."""

    url = f"https://api.stagingeb.com/v1/properties/{id}"

    response = make_request(url)

    # Information fields
    public_id = response["public_id"]
    title = response["title"]
    description = response["description"]
    
    if len(response['property_images']):
        image_url = response["property_images"][0]["url"]
        image_title = response["property_images"][0]["title"]
    else:
        image_url = '/'
        image_title = response["public_id"]

    property_type = response["property_type"]
    location = response["location"]["name"]
    form = contact_request(request, public_id)

    context = {
        'public_id': public_id,
        'title': title,
        'description': description,
        'image_url': image_url,
        'image_title': image_title,
        'property_type': property_type,
        'location': location,
        'form': form,
    }

    return render(request, 'EBApi/property.html', context)

#########
# FORMS #
#########

def contact_request(request, id):
    """Send a client's contact request."""

    if request.method != 'POST':
        form = ContactRequestForm(initial={'public_id': id})
    else:
        form = ContactRequestForm(data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            send_request(JsonResponse(data))
            return redirect('EBApi:property', id=id)

    return form

EBApi/templates/EBApi/properties.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EB Test</title>
</head>
<body>
    <h1>Propiedades</h1>

    <div class="navigation" style="display: flex; justify-content: center; gap: 2em;">
        {% if previous_page %}
        <form action="{% url 'EBApi:properties' page=previous_page %}">
            <input type="submit" value="<" />
        </form>
        {% endif %}
        {% if next_page %}
        <form action="{% url 'EBApi:properties' page=next_page %}">
            <input type="submit" value=">" />
        </form>
        {% endif %}
    </div>

    <br>

    <div class="container">
        <div class="properties"  style="display: flex; flex-wrap: wrap; flex: 1; gap: 2em; align-items: top; justify-content: center;">
            {% for property in properties %}
            <div class="property" style="border: solid; border-color: black; padding: 1em;">
                <p>
                    Public ID: 
                    <a href="{% url 'EBApi:property' id=property.public_id %}">
                        {{ property.public_id }}
                    </a>
                </p>
                <p>Title: {{ property.title }}</p>
                <p>Property type: {% for operation in property.operations %}{{ operation.type }}{% endfor %}</p>
                <p>Location: {{ property.location }}</p>
                <img src="{{ property.title_image_thumb }}" alt="{{ property.public_id }}-image" style="display: block; margin-left: auto; margin-right: auto;">
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

EBApi/templates/EBApi/property.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EB Test</title>
</head>
<body>
    <form action="{% url 'EBApi:properties' %}">
        <input type="submit" value="Regresar a propiedades" />
    </form>
    <h1>{{ title }}</h1>
    <h3>{{ public_id }}</h3>
    <p>{{ property_type }}</p>
    <p>{{ location }}</p>
    <p>{{ description }}</p>
    <img src="{{ image_url }}" alt="{{ image_title }}" style="width: 50em;">

    <form action="{% url 'EBApi:contact_requests' id=public_id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">
            Send contact request
        </button>
    </form>
    
</body>
</html>